/* eslint-disable */
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

declare module "@apollo/client" {

  export function useQuery(source: "\n  query OAuthLoggedInUser {\n    me {\n      id\n      name\n      email\n      imageUrl(height: 90)\n      type\n    }\n  }\n"): typeof import('./graphql').OAuthLoggedInUserDocument;
  export function useQuery(source: "\n  query ContributorsDashboard(\n    $slug: String\n    $firstDayOfMonth: DateTime\n    $firstDayOfPastMonth: DateTime\n    $firstDayOfPreviousMonth: DateTime\n  ) {\n    account(slug: $slug) {\n      slug\n      name\n      memberOf(role: BACKER, orderBy: { field: TOTAL_CONTRIBUTED, direction: DESC }) {\n        nodes {\n          id\n          account {\n            slug\n            name\n            stats {\n              totalAmountReceivedPastMonth: totalAmountReceived(\n                dateFrom: $firstDayOfPastMonth\n                dateTo: $firstDayOfMonth\n                includeChildren: true\n              ) {\n                value\n                currency\n              }\n              totalAmountSpentPastMonth: totalAmountSpent(\n                dateFrom: $firstDayOfPastMonth\n                dateTo: $firstDayOfMonth\n                includeChildren: true\n              ) {\n                value\n                currency\n              }\n              totalAmountReceivedPreviousMonth: totalAmountReceived(\n                dateFrom: $firstDayOfPreviousMonth\n                dateTo: $firstDayOfPastMonth\n                includeChildren: true\n              ) {\n                value\n                currency\n              }\n              totalAmountSpentPreviousMonth: totalAmountSpent(\n                dateFrom: $firstDayOfPreviousMonth\n                dateTo: $firstDayOfPastMonth\n                includeChildren: true\n              ) {\n                value\n                currency\n              }\n              balance(includeChildren: true) {\n                value\n                currency\n              }\n              activeMonthlyRecurringContributions: activeRecurringContributionsV2(frequency: MONTHLY) {\n                value\n                currency\n              }\n              activeYearlyRecurringContributions: activeRecurringContributionsV2(frequency: YEARLY) {\n                value\n                currency\n              }\n            }\n          }\n          totalDonations {\n            value\n            currency\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').ContributorsDashboardDocument;
  export function useQuery(source: string): unknown;

    export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<    infer TType,    any  >    ? TType    : never;  
}